# Generated by Django 5.0 on 2024-09-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='1:1 Nisbatdagi rasm yuklang', upload_to='medicine_images/', verbose_name='Rasm')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Matn')),
                ('description_uz', models.TextField(null=True, verbose_name='Matn')),
                ('description_ru', models.TextField(null=True, verbose_name='Matn')),
                ('description_en', models.TextField(null=True, verbose_name='Matn')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='1:1 Nisbatdagi rasm yuklang', upload_to='news_images/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('slug', models.SlugField(default='', verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Matn')),
                ('content_uz', models.TextField(null=True, verbose_name='Matn')),
                ('content_ru', models.TextField(null=True, verbose_name='Matn')),
                ('content_en', models.TextField(null=True, verbose_name='Matn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
        ),
    ]
