# Generated by Django 5.0 on 2024-09-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(help_text='1:1 Nisbatdagi rasm yuklang', upload_to='assets/images/medicine_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(help_text='1:1 Nisbatdagi rasm yuklang', upload_to='assets/images/news_images/', verbose_name='Rasm'),
        ),
    ]
