# Generated by Django 5.0 on 2024-11-11 14:34

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_medicine_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='name',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name_en',
            field=models.CharField(default='', max_length=200, verbose_name='Nomi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name_ru',
            field=models.CharField(default='', max_length=200, verbose_name='Nomi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name_uz',
            field=models.CharField(default='', max_length=200, verbose_name='Nomi'),
            preserve_default=False,
        ),
    ]
